### ISSUE TITLE
Etapissa virhe? CRUD - Viikko 3

### ISSUE THREAD

**Issue by Mirex97** [materiaalit/tsoha-18#11]
Viikko 3 etapissa lukee "täysi CRUD-toiminnallisuus sovelluksen kautta" niin eikö tämä tarkoita
"Create, Read, Update, Delete". 
Miksi tämän jälkeen lukee:

"(**kaikkien rivien listaus**, yhden rivin tietojen näyttö, 
yhden rivin tietojen muokkaus, yhden rivin tietojen poisto)"

Eikös tuon "kaikkien rivien listaus" pitäisi olla **yhden rivin tietojen luonti**?

T. Mirex

**Comment by avihavai** [comment]
Hyvä bongaus, täydennän. Tuossa tavoitteena myös listaus. Arvostelussa toki mennään kummalla tahansa (eli alkuperäisten bugisten tavoitteiden täyttö myös ok).
