### ISSUE TITLE
Rikkinäinen linkki Python-kielen alkeissa

### ISSUE THREAD

**Issue by strajama** [materiaalit/tsoha-18#24]
Python-alkeet -luvun 1.1 -osassa on rikkinäinen linkki "Kurssin työvälineet". Se yrittää avata osoitetta https://materiaalit.github.io/tsoha-18/python-alkeet/tyovalineet/ kun oikea olisi https://materiaalit.github.io/tsoha-18/tyovalineet/

**Comment by qzuw** [comment]
Korjattu, kiitos!
